# Generated by Django 5.1.1 on 2024-09-14 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_alter_myuser_companys'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='salary',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
