# Generated by Django 5.1.1 on 2024-09-14 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0004_alter_myuser_date_joined'),
        ('companys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='companys',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='companys.company'),
        ),
    ]
