# Generated by Django 5.1.1 on 2024-09-17 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
        ('role', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='company',
        ),
        migrations.AddField(
            model_name='role',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='departments.department'),
        ),
    ]
