# Generated by Django 5.1.1 on 2024-09-17 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companys', '0002_remove_company_contact_info_company_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='name',
            new_name='company_name',
        ),
    ]
